01-button-solution
js-tasks-ru/htmlcss-20221107_rustam08 pull request #3
Opened 2022-11-18 12:21 UTC by Rustam346

2022-11-18 12:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-18 14:01 UTC, GSemikozov requested changes

2022-11-18 14:01 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    cursor: default;
чтобы пользователь не мог нажимать лучше добавить pointer-events: none

2022-11-18 14:01 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    transition: opacity 200ms ease-in-out, backround 200ms ease-in-out;
общий для всех типов кнопок транзишн можно сразу задать на уровне .button

2022-11-18 14:01 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    cursor: default;
чтобы пользователь не мог нажимать лучше добавить pointer-events: none

2022-11-18 14:01 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    width: 182px;
ширину не стоит фиксировать (длинный текст покажет проблему)

2022-11-18 14:01 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    background: #4263EB;
везде надо использовать переменные (глобальные лежат в main.css). Использование : `var(--var-name)`

2022-11-23 12:16 UTC, Rustam346 commented on 03-lection1/01-button/botton.css
> +    background: #4263EB;
у меня не работают переменые, я как только не пробывал подключать стили, а они все равно не работают

2022-11-23 23:07 UTC, GSemikozov requested changes

2022-11-23 23:07 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    background: #4263EB;
а все же - как именно и где они определены, и как подключаются?

2022-11-24 21:39 UTC, GSemikozov requested changes

2022-11-24 21:39 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +    color: #ffffff;
для белого цвета переменная тоже есть

2022-11-24 21:39 UTC, GSemikozov commented on 03-lection1/01-button/botton.css
> +@import '../../assets/css/main.css';
наоборот - файл стилей подключаем внутри main.css

2022-11-24 21:39 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <link rel="stylesheet" href="./assets/css/main.css">
переменные потому и не видны были, потому что файл подключен неправильно - изначально ведь было как надо, зачем менялось?)

2022-11-25 11:05 UTC, GSemikozov approved these changes

2022-11-25 11:05 UTC, merged